# Generated by Django 3.0.4 on 2020-03-22 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес')),
                ('construction_year', models.PositiveIntegerField(db_index=True, verbose_name='Год постройки')),
            ],
        ),
        migrations.CreateModel(
            name='BricksTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(verbose_name='Количество кирпичей')),
                ('date', models.DateField(verbose_name='Дата создания')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brick_tasks', to='building.Building', verbose_name='Задание на кладку')),
            ],
        ),
    ]
